// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqayhqfntpqzbpbkrkvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxYXlocWZudHBxemJwYmtya3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0ODkxMTQsImV4cCI6MjA2ODA2NTExNH0.iUcAp9cidNjl0TVWxP6nJl-A0kKGIhgd1QPW8fDSnM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});